# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
  #Download the config.csv file on the agent
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'SP - NTO'
      ScriptType: 'InlineScript'
      Inline: |
        $BlobFilePath = 'config.csv' # Relative path in blob starting from container
        $OutputFilePath = '.' # Path to download the file to
        $StorageAccountName = 'configsavm'
        $ContainerName = 'mycontainer'

        # Prompt for Azure Account creds, if working from VM with managed identity could add also switch -Identity to use that identity directly
        $StorageContext = New-AzStorageContext -StorageAccountName $StorageAccountName

        Get-AzStorageBlobContent -Blob $BlobFilePath -Container $ContainerName -Destination $OutputFilePath -Context $StorageContext
      azurePowerShellVersion: 'LatestVersion'

  #Install the different files from the Az Copy folder
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
        Install-Module Az.Accounts -Scope CurrentUser -Force
        Install-Module AzureAD


  #Copy the CSV configurations files from the storage account

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'SP - NTO'
      ScriptType: 'FilePath'
      ScriptPath: 'Create-Vms.ps1'
      ScriptArguments: '-IfExist "Error"'
      azurePowerShellVersion: 'LatestVersion'